### PR TITLE
Key search

### PR DESCRIPTION
**Pull request by oneiros**
Here is a first draft of the key search feature.

After selecting an environment, one can now choose a node as before _or_ search for key:

image

When searching for a key a results page is displayed that mostly copies the UI we already have for nodes:

image

Clicking on a file name opens up the display of the actual value, just as in the node view:

image

This includes a _massive_ refactoring of a lot of things. I am mostly happy with this, except for the git backend "problem" we talked about.

When this looks like it is going in the right direction, I would like to add a couple more tests.

### CODE REVIEW

**Comment by tuxmea** [comment]
Can you please specify how the ui is going to look if you have several (maybe 50, maybe 100) node specific yaml files which have the key inside?

**Comment by oneiros** [comment]
It is a long list then:

image

**Comment by tuxmea** [comment]
1. Please add a separator or "**OR**" line between the Fields "select node" and "search for a key"
2. Please make the result collapsible

**Comment by oneiros** [comment]
Hierarchies are now collapsed by default. Also, I added a few tests. This should be ready now. Fixes #4

**Pull request merged**
